# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-13 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntaps_update_status', '0003_auto_20171012_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(max_length=160),
        ),
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.TextField(max_length=160),
        ),
    ]
