# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-13 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntaps_profile', '0002_auto_20171013_0121'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='birthday',
            field=models.CharField(default='Unknown', max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='description',
            field=models.CharField(default='Unknown', max_length=140),
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='Unknown', max_length=254),
        ),
        migrations.AddField(
            model_name='profile',
            name='expertise',
            field=models.CharField(default='null', max_length=140),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(default='Unknown', max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='Unknown', max_length=30),
        ),
    ]
